# Generated by Django 3.1 on 2020-08-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Titel')),
                ('album', models.CharField(max_length=40, verbose_name='Album')),
                ('year', models.IntegerField(verbose_name='Erscheinungsjahr')),
                ('info', models.TextField(verbose_name='Info')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_request.band', verbose_name='Band')),
            ],
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('songs', models.ManyToManyField(to='song_request.Song', verbose_name='Songs')),
            ],
        ),
    ]
