# Generated by Django 3.1 on 2020-08-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_request', '0002_auto_20200810_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='year',
            new_name='published',
        ),
    ]
