# Generated by Django 3.1 on 2020-08-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_request', '0004_auto_20200815_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archivsong'),
        ),
        migrations.AlterField(
            model_name='song',
            name='info',
            field=models.TextField(default='keine', verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default='keine', verbose_name='Lyrics'),
        ),
    ]
