# Generated by Django 3.1 on 2020-08-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_request', '0005_auto_20200815_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsal',
            name='songs',
            field=models.ManyToManyField(default=None, to='song_request.Song', verbose_name='Songs'),
        ),
    ]
