# Generated by Django 3.1 on 2020-08-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_request', '0007_rehearsal_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='published',
            field=models.IntegerField(default=0, verbose_name='Erscheinungsjahr'),
        ),
    ]
